# Generated by Django 4.0.1 on 2022-01-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=5)),
                ('tracking_number', models.CharField(max_length=40)),
                ('label', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
